import {test,expect} from '@playwright/test';
test('separate hotbar and table share actions and rolls without duplicate dice canvases',async({page,context})=>{
 test.setTimeout(60000);
 await page.goto('/');
 await page.getByPlaceholder('Dungeon Master').fill('Split wizard');
 await page.getByRole('button',{name:/Create a room/}).click();
 await expect(page.getByRole('button',{name:'Roll dice',exact:true})).toBeEnabled();
 const table=await context.newPage(),bar=await context.newPage();
 await table.setViewportSize({width:420,height:640});
 await bar.setViewportSize({width:1000,height:280});
 const link=page.url()+'&overlay=1&desktop=1&surface=';
 await table.goto(link+'table');await bar.goto(link+'hotbar');
 await expect(table.locator('.console-head .live')).toHaveText('LIVE');
 await expect(bar.getByRole('button',{name:'Roll',exact:true})).toBeEnabled();
 await expect(bar.locator('canvas')).toHaveCount(0);
 await expect(table.locator('.rpg-hotbar')).toHaveCount(0);
 await expect(table.locator('.dice-panel canvas')).toBeVisible();
 await bar.getByText('Manage actions',{exact:true}).click();
 await bar.getByLabel('Action name',{exact:true}).fill('Magic missile');
 await bar.getByLabel('Action dice',{exact:true}).fill('3d4+3');
 await bar.getByRole('button',{name:'Add action',exact:true}).click();
 await bar.getByText('Manage actions',{exact:true}).click();
 await expect(page.getByRole('button',{name:'Roll Magic missile',exact:true})).toBeVisible();
 const response=bar.waitForResponse(r=>r.url().endsWith('/api/session')&&r.request().method()==='POST'&&r.request().postDataJSON()?.action==='roll');
 await bar.getByRole('button',{name:'Roll Magic missile',exact:true}).click();
 const result=await(await response).json();
 await expect(table.locator('.roll-reveal')).toContainText('Split wizard',{timeout:20000});
 await expect(table.locator('.roll-entry')).toContainText('Magic missile');
 await expect(bar.locator('.desktop-result')).toContainText('= '+result.total);
 await table.screenshot({path:'test-results/split-table.png'});
 await bar.screenshot({path:'test-results/split-hotbar.png'});
 for(const win of [table,bar])expect(await win.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
});
